### PR TITLE
Add Twisted adapter and interceptors

### LINKED ISSUE #1: Twisted Web interceptor and adapter
Twisted Web and Nevow share a lot of code, it should be fairly straightforward to write a Twisted Web interceptor and adapter that leverages the existing Nevow code.

### PR DESCRIPTION
**Pull request by ddormer**
Closes #1

---
This change is [Reviewable](https://reviewable.io/reviews/jonathanj/fugue/7)

### CODE REVIEW

**Comment by ddormer** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/fugue/adapters/twisted.py, line 12 at r1](https://reviewable.io/reviews/jonathanj/fugue/7#-LEUx5lr8Qeoer8EwfrD:-LEVGQ_t0y2cPi6uPjro:b-896fix) ([raw file](https://github.com/jonathanj/fugue/blob/377966eff99730b559161700c2247cff6c3f7fc2/src/fugue/adapters/twisted.py#L12)):*
<details><summary><i>Previously, jonathanj (Jonathan Jacobs) wrote…</i></summary><blockquote>

You haven't implemented all of `IResource`: https://twistedmatrix.com/documents/current/api/twisted.web.resource.IResource.html

The interface says `getChildWithDefault` will not be called on leaf resources, but you probably want to raise `NotImplementedError` for `putChild`.
</blockquote></details>

Done.

---

*[src/fugue/interceptors/nevow.py, line 97 at r1](https://reviewable.io/reviews/jonathanj/fugue/7#-LEUxucpDZWcvC_0EKX_:-LEVGqSyCZ1yIN0kjPsK:b-pvyfk5) ([raw file](https://github.com/jonathanj/fugue/blob/377966eff99730b559161700c2247cff6c3f7fc2/src/fugue/interceptors/nevow.py#L97)):*
<details><summary><i>Previously, jonathanj (Jonathan Jacobs) wrote…</i></summary><blockquote>

Perhaps `_enter_nevow_inner` is a better name? If this function ever appears in a traceback `_inner` is not uniquely identifiable within this file.
</blockquote></details>

That's a good point, I've updated these.

---

*[src/fugue/interceptors/nevow.py, line 112 at r1](https://reviewable.io/reviews/jonathanj/fugue/7#-LEUy5V988bdSFPWtpCq:-LEVGq6O3d6wKHP6j-VI:b-896fix) ([raw file](https://github.com/jonathanj/fugue/blob/377966eff99730b559161700c2247cff6c3f7fc2/src/fugue/interceptors/nevow.py#L112)):*
<details><summary><i>Previously, jonathanj (Jonathan Jacobs) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.

---

*[src/fugue/interceptors/nevow.py, line 134 at r1](https://reviewable.io/reviews/jonathanj/fugue/7#-LEUyDWaB0t0Vc5yN0nh:-LEVGv0iEoWrP6CL3XoH:b-896fix) ([raw file](https://github.com/jonathanj/fugue/blob/377966eff99730b559161700c2247cff6c3f7fc2/src/fugue/interceptors/nevow.py#L134)):*
<details><summary><i>Previously, jonathanj (Jonathan Jacobs) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.

---

*[src/fugue/interceptors/twisted.py, line 12 at r1](https://reviewable.io/reviews/jonathanj/fugue/7#-LEUzJK38lo5tcBqUND6:-LEVKTWjAYy-48mP8La-:b-3lip7t) ([raw file](https://github.com/jonathanj/fugue/blob/377966eff99730b559161700c2247cff6c3f7fc2/src/fugue/interceptors/twisted.py#L12)):*
<details><summary><i>Previously, jonathanj (Jonathan Jacobs) wrote…</i></summary><blockquote>

You'll need to finish this request too. Perhaps it would be better to turn `_finish_request` into a decorator so that you can do `_error_twisted = _finish_request(_error_nevow(TWISTED_REQUEST))` and `@_finish_request;; def _leave_twisted``.
</blockquote></details>

The decorator felt significantly more confusing to read so I moved `_finish_request` out on it's own and called it from the `_leave_twisted` and `_error_twisted` functions. If you feel a decorator is still better I can give it another go.

---

*[src/fugue/test/adapters/test_twisted.py, line 35 at r1](https://reviewable.io/reviews/jonathanj/fugue/7#-LEUzrPj7mopZDVjsH3t:-LEVKMMbCNjdhQWLb9j6:b-896fix) ([raw file](https://github.com/jonathanj/fugue/blob/377966eff99730b559161700c2247cff6c3f7fc2/src/fugue/test/adapters/test_twisted.py#L35)):*
<details><summary><i>Previously, jonathanj (Jonathan Jacobs) wrote…</i></summary><blockquote>

Can we either use consistent newline styling here or just make this one line?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/jonathanj/fugue/7)*

**Comment by jonathanj** [comment]
Reviewed 4 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/fugue/adapters/twisted.py, line 25 at r2](https://reviewable.io/reviews/jonathanj/fugue/7#-LEVhwJCCeqkT1eAMsNA:-LEVhwJCCeqkT1eAMsNB:b-4384d4) ([raw file](https://github.com/jonathanj/fugue/blob/21b6311dd55bf3afad6e35a3e68edd83f4101e8d/src/fugue/adapters/twisted.py#L25)):*
> ```Python
> 
>     def putChild(self, path, child):
>         raise NotImplementedError
> ```

You'll want to actually instantiate the error.

---

*[src/fugue/interceptors/twisted.py, line 12 at r1](https://reviewable.io/reviews/jonathanj/fugue/7#-LEUzJK38lo5tcBqUND6:-LEVoRcX5mFJhYQpai1K:b-bespdh) ([raw file](https://github.com/jonathanj/fugue/blob/377966eff99730b559161700c2247cff6c3f7fc2/src/fugue/interceptors/twisted.py#L12)):*
<details><summary><i>Previously, ddormer (Darren Dormer) wrote…</i></summary><blockquote>

The decorator felt significantly more confusing to read so I moved `_finish_request` out on it's own and called it from the `_leave_twisted` and `_error_twisted` functions. If you feel a decorator is still better I can give it another go.
</blockquote></details>

Okay, sorry to mess you around but I noticed that `_leave_twisted` may have an issue if `_leave_nevow` raises, namely `finish` will never be called. Thinking about this a little more, the correct place to call finish is in `_send_response`, since that's the only place writing occurs and is ultimately the last place it should occur.

My suggestion is to have an additional argument to the `_{enter,leave}_nevow` functions called `finish`, that defaults to some `_noop` function, and call `finish(context)` at the end of `_send_response`.

This also has the benefit of making your `_{enter,leave,error}_twisted` functions be simple assignments instead of full body function definitions.

---

*[src/fugue/interceptors/twisted.py, line 12 at r2](https://reviewable.io/reviews/jonathanj/fugue/7#-LEVl78OBN3H0jYM9mGS:-LEVl78OBN3H0jYM9mGT:bayg04q) ([raw file](https://github.com/jonathanj/fugue/blob/21b6311dd55bf3afad6e35a3e68edd83f4101e8d/src/fugue/interceptors/twisted.py#L12)):*
> ```Python
> 
> 
> def _finish_request(context):
> ```

Can you add a docstring?

---


*Comments from [Reviewable](https://reviewable.io/reviews/jonathanj/fugue/7)*

**Comment by ddormer** [comment]
Review status: 4 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/fugue/adapters/twisted.py, line 25 at r2](https://reviewable.io/reviews/jonathanj/fugue/7#-LEVhwJCCeqkT1eAMsNA:-LEW9egp7OXtCQcYbxSA:b-896fix) ([raw file](https://github.com/jonathanj/fugue/blob/21b6311dd55bf3afad6e35a3e68edd83f4101e8d/src/fugue/adapters/twisted.py#L25)):*
<details><summary><i>Previously, jonathanj (Jonathan Jacobs) wrote…</i></summary><blockquote>

You'll want to actually instantiate the error.
</blockquote></details>

Done.

---

*[src/fugue/interceptors/twisted.py, line 12 at r1](https://reviewable.io/reviews/jonathanj/fugue/7#-LEUzJK38lo5tcBqUND6:-LEW9_yn0peSXP9nRPrc:b-896fix) ([raw file](https://github.com/jonathanj/fugue/blob/377966eff99730b559161700c2247cff6c3f7fc2/src/fugue/interceptors/twisted.py#L12)):*
<details><summary><i>Previously, jonathanj (Jonathan Jacobs) wrote…</i></summary><blockquote>

Okay, sorry to mess you around but I noticed that `_leave_twisted` may have an issue if `_leave_nevow` raises, namely `finish` will never be called. Thinking about this a little more, the correct place to call finish is in `_send_response`, since that's the only place writing occurs and is ultimately the last place it should occur.

My suggestion is to have an additional argument to the `_{enter,leave}_nevow` functions called `finish`, that defaults to some `_noop` function, and call `finish(context)` at the end of `_send_response`.

This also has the benefit of making your `_{enter,leave,error}_twisted` functions be simple assignments instead of full body function definitions.
</blockquote></details>

Done.

---

*[src/fugue/interceptors/twisted.py, line 12 at r2](https://reviewable.io/reviews/jonathanj/fugue/7#-LEVl78OBN3H0jYM9mGS:-LEWA4o91Qa2-k4usE2r:b-896fix) ([raw file](https://github.com/jonathanj/fugue/blob/21b6311dd55bf3afad6e35a3e68edd83f4101e8d/src/fugue/interceptors/twisted.py#L12)):*
<details><summary><i>Previously, jonathanj (Jonathan Jacobs) wrote…</i></summary><blockquote>

Can you add a docstring?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/jonathanj/fugue/7)*

**Comment by jonathanj** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/jonathanj/fugue/7#-:-LEeXT5F7C7ZzAtlBPid:bnfp4nl)*

**Pull request merged**
